import React from 'react';
import {PushNotificationIOS} from 'react-native';
import PushNotification from 'react-native-push-notification';

function phoneNumberToID(phoneNumber){
  var replaceChars={ "-":"" , "(":"", ")":"", " ":"", };
  var id = phoneNumber.replace(/-|\(|\)|\s/g,function(match) {return replaceChars[match];});
  return id;
}

export function add(contact){
  var message = `${contact.contactMethod} ${contact.firstName} ${contact.lastName} today!`;
  let d = new Date(contact.nextContact);
  var day = new Date(d.getFullYear(),d.getMonth(),d.getDay(),9,0,0);
  var id = phoneNumberToID(contact.phoneNumber);

  PushNotification.localNotificationSchedule({
    /* Android Only Properties */
   id: id, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
   ticker: "My Notification Ticker", // (optional)
   autoCancel: true, // (optional) default: true
   largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
   smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
   bigText: message, // (optional) default: "message" prop
   color: "blue", // (optional) default: system default
   vibrate: true, // (optional) default: true
   vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
   priority: "high", // (optional) set notification priority, default: high
   visibility: "private", // (optional) set notification visibility, default: private
   importance: "high", // (optional) set notification importance, default: high

   /* iOS and Android properties */
   title: "Today's Pings", // (optional)
   number: id,
   message: message, // (required)
   playSound: true, // (optional) default: true
   soundName: 'default', // (optional) Sound to play when the notification is shown
   date: day
  });
  return
}

export function remove(contact){
  PushNotification.cancelLocalNotifications({id: phoneNumberToID(contact.phoneNumber)});
  return
}
export function update(contact){
  remove(contact);
  add(contact);
}

// function newNotification2(day, notifDicEntry){
//   let topName = notifDicEntry[0]
//   let otherCount = notifDicEntry[1]
//   let id = notifDicEntry[2]
//
//   var day = new Date(day);
//   console.log(day);
//   if(otherCount == 0){
//     message = `You should ping ${topName} today!`
//   }
//   else if(otherCount == 1){
//       message = `You should ping ${topName} and ${otherCount} other today!`
//   }
//   else{
//       message = `You should ping ${topName} and ${otherCount} others today!`
//   }
//   PushNotification.localNotificationSchedule({
//     /* Android Only Properties */
//    id: id, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
//    ticker: "My Notification Ticker", // (optional)
//    autoCancel: true, // (optional) default: true
//    largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
//    smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
//    bigText: message, // (optional) default: "message" prop
//    color: "blue", // (optional) default: system default
//    vibrate: true, // (optional) default: true
//    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
//    priority: "high", // (optional) set notification priority, default: high
//    visibility: "private", // (optional) set notification visibility, default: private
//    importance: "high", // (optional) set notification importance, default: high
//
//    /* iOS and Android properties */
//    title: "Today's Pings", // (optional)
//    number: id,
//    message: message, // (required)
//    playSound: true, // (optional) default: true
//    soundName: 'default', // (optional) Sound to play when the notification is shown
//    date: day
//   });
// }
// // export default function removeNotification(day){
// //
// // }
